from flask import Blueprint, render_template, session, flash, request, redirect, url_for
from ..services.ai_service import generate_email
from ..services.supabase_service import fetch_data, insert_data

bp = Blueprint("dashboard", __name__, url_prefix="/dashboard")


@bp.route("/", methods=["GET", "POST"])
def index():
    """
    Dashboard route to handle email generation and display previously generated emails.
    """
    if request.method == "POST":
        # # Get the prompt from the form
        # prompt = request.form.get("prompt")

        # # Check if prompt is provided
        # if not prompt:
        #     flash("Prompt is required!", "error")
        #     return render_template("dashboard.html", emails=[])

        # # Generate email content using AI service
        # email_content = generate_email(prompt)

        # # Get the user ID from session
        # user_id = session.get("user", {}).get("id")

        # # Save generated email in the database if user is logged in
        # if user_id:
        #     insert_data("generated_emails", {"user_id": user_id, "email_content": email_content})

        # Display the generated email
        return render_template("dashboard.html")

    # If GET request, fetch and display emails generated by this user
    user_id = session.get("user", {}).get("id")
    emails = fetch_data("generated_emails", {"user_id": user_id}) if user_id else []
    return render_template("dashboard.html", emails=emails)


@bp.route("/coming_soon")
def coming_soon():
    """
    Coming Soon route to display a placeholder page for features under development.
    """
    return render_template("coming_soon.html")


@bp.route("/feature/<feature_name>")
def feature_redirect(feature_name):
    """
    Redirect to a specific feature page or show a coming soon page if the feature is unavailable.
    """
    available_features = ["generate_email", "write_sop", "career_pathway", "write_lor", "course_recommendations"]
    
    if feature_name in available_features:
        # return redirect(url_for(f"dashboard.{feature_name}"))
        return redirect(url_for("dashboard.coming_soon"))
    else:
        flash(f"The {feature_name} feature is coming soon!", "info")
        return redirect(url_for("dashboard.coming_soon"))


# Example placeholders for the features
@bp.route("/generate_email")
def generate_email_feature():
    return render_template("generate_email.html")


@bp.route("/write_sop")
def write_sop_feature():
    return render_template("write_sop.html")


@bp.route("/career_pathway")
def career_pathway_feature():
    return render_template("career_pathway.html")


@bp.route("/write_lor")
def write_lor_feature():
    return render_template("write_lor.html")


@bp.route("/course_recommendations")
def course_recommendations_feature():
    return render_template("course_recommendations.html")
